import React, { Component } from 'react'
import { Grid } from 'semantic-ui-react'
import { connect } from 'react-redux'
import axios from 'axios'
import UIAvatar from 'react-ui-avatars'
import { Card, Icon, Image } from 'semantic-ui-react'
import history from '../../utils/history'

class ProfilePage extends Component {
  constructor(props) {
    super(props)
    this.state = {
      userName: '',
      userEmail: '',
    }
  }
  componentDidMount(match) {
    let url = `${process.env.REACT_APP_JSON_BASE_URL}users/${this.props.userId}`
    axios.get(url).then(response => {
      if (response.data)
        this.setState({
          userName: response.data && response.data.username,
          userEmail: response.data && response.data.email,
        })
    })
  }
  render() {
    const isLoggedIn = Object.keys(this.props.user).length !== 0
    if (!isLoggedIn) {
      history.push('/')
    }
    console.log(this.props)
    const { userName, userEmail } = this.state
    return (
      <Grid columns={1} divided>
        <Grid.Row>
          <Grid.Column>
            <Card>
              <UIAvatar
                name={userName}
                size={512}
                length={userName.length - 3}
                bold={true}
              />
              <Card.Content>
                <Card.Header>{userName}</Card.Header>
                <Card.Meta>
                  <span className="date">Joined in 2015</span>
                </Card.Meta>
                <Card.Description>
                  {userName} is an emerging developer in Waterford.
                </Card.Description>
              </Card.Content>
              <Card.Content extra>
                <a>
                  <Icon name="user" />
                  We autogenerated your Avatar using your Name!
                </a>
              </Card.Content>
            </Card>
          </Grid.Column>
        </Grid.Row>
      </Grid>
    )
  }
}

const mapStateToProps = state => {
  return {
    user: state.user,
    userId: state.id,
  }
}
export default connect(
  mapStateToProps,
  null
)(ProfilePage)
